version: 0.2

phases:
  install:
    commands:
      - apt-get -qq update && apt-get -qq install -y gnupg software-properties-common curl
      - wget -nv -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get -qq update
      - apt-get -qq install -y terraform git

  build:
    commands:
      - echo "Hello world"
      - ls